#!/usr/bin/env python3
"""
gen_unity_meta.py — emit deterministic Unity .meta files for new source files
and folders that were authored outside the editor.

This repo commits a .meta for every .cs/.shader (the content validator treats a
missing script .meta as a HARD error — references break without a stable GUID).
Since the art-pipeline work is authored on Linux with no Unity editor, this
generates those metas deterministically:

  GUID = md5(repo-relative-path)  -> stable, unique, collision-checked against
  every GUID already committed in the repo.

Scope (safe subset only):
  * .cs files                -> MonoImporter meta (REQUIRED by the validator)
  * folders                  -> folderAsset meta (consistency)
Binary assets (.glb/.png) are intentionally skipped: their importers
(glTFast ScriptedImporter, TextureImporter) must be generated by Unity on first
import. A hand-written importer block would be wrong; a missing binary meta is
only a soft warning.
"""

import hashlib
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

FOLDER_META = ("fileFormatVersion: 2\nguid: {guid}\nfolderAsset: yes\n"
               "DefaultImporter:\n  externalObjects: {{}}\n  userData:\n"
               "  assetBundleName:\n  assetBundleVariant:\n")

SCRIPT_META = ("fileFormatVersion: 2\nguid: {guid}\nMonoImporter:\n"
               "  externalObjects: {{}}\n  serializedVersion: 2\n"
               "  defaultReferences: []\n  executionOrder: 0\n"
               "  icon: {{instanceID: 0}}\n  userData:\n  assetBundleName:\n"
               "  assetBundleVariant:\n")


def guid_for(relpath):
    return hashlib.md5(relpath.encode("utf-8")).hexdigest()  # 32 hex = Unity GUID


def existing_guids():
    guids = set()
    for dp, _, fns in os.walk(os.path.join(REPO, "Assets")):
        for fn in fns:
            if fn.endswith(".meta"):
                try:
                    txt = open(os.path.join(dp, fn), encoding="utf-8", errors="ignore").read()
                    m = re.search(r"guid:\s*([0-9a-f]{32})", txt)
                    if m:
                        guids.add(m.group(1))
                except Exception:
                    pass
    return guids


def main():
    roots = sys.argv[1:] or ["Assets/Art", "Assets/ThirdParty",
                             "Assets/Game/Code/Editor/ArtPipeline",
                             "Assets/Game/Code/Track/Dressing"]
    used = existing_guids()
    created = 0

    def emit(target_path, template):
        nonlocal created
        meta = target_path + ".meta"
        if os.path.exists(meta):
            return
        rel = os.path.relpath(target_path, REPO).replace("\\", "/")
        g = guid_for(rel)
        salt = 0
        while g in used:
            salt += 1
            g = guid_for(rel + "#" + str(salt))
        used.add(g)
        with open(meta, "w") as f:
            f.write(template.format(guid=g))
        created += 1

    for root in roots:
        abs_root = os.path.join(REPO, root)
        if not os.path.exists(abs_root):
            continue
        # folder meta for the root itself
        emit(abs_root, FOLDER_META)
        for dp, dirnames, filenames in os.walk(abs_root):
            for d in dirnames:
                emit(os.path.join(dp, d), FOLDER_META)
            for fn in filenames:
                if fn.endswith(".meta") or fn.startswith("."):
                    continue
                if fn.endswith(".cs"):
                    emit(os.path.join(dp, fn), SCRIPT_META)

    print("gen_unity_meta: created %d .meta files" % created)


if __name__ == "__main__":
    main()
